# Hello World

In [1]:
import numpy as np

In [2]:
matrix = np.array([[0., 1., 2.,], [1., 2., 3.,]])
matrix2 = np.array([[0., 1.,], [0., 1.,], [0., 1.,]])

In [3]:
print(matrix, matrix.ndim, matrix.shape)
print(matrix2, matrix2.ndim, matrix2.shape)

[[0. 1. 2.]
 [1. 2. 3.]] 2 (2, 3)
[[0. 1.]
 [0. 1.]
 [0. 1.]] 2 (3, 2)


In [4]:
print(np.concatenate([matrix[:, -1], matrix[0, :]], axis=0))
print(np.stack([matrix[0, :], np.concatenate([[0], matrix[:, -1]])], axis=0))

[2. 3. 0. 1. 2.]
[[0. 1. 2.]
 [0. 2. 3.]]


In [5]:
print(np.matmul(matrix, matrix2))
print(np.max(matrix, axis=0))
print(np.argmax(matrix, axis=0))
print(np.mean(matrix2, axis=-1))

[[0. 3.]
 [0. 6.]]
[1. 2. 3.]
[1 1 1]
[0.5 0.5 0.5]


In [6]:
print(np.reshape(matrix, [-1, 1]))
print(np.squeeze(np.reshape(matrix, [-1, 1])))
print(np.reshape(matrix2, [2, -1]))

[[0.]
 [1.]
 [2.]
 [1.]
 [2.]
 [3.]]
[0. 1. 2. 1. 2. 3.]
[[0. 1. 0.]
 [1. 0. 1.]]


In [7]:
print(np.zeros_like(matrix))
print(np.ones_like(matrix2.T))
print(np.random.randn(5, 5))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[ 0.73390224  0.76041494 -0.86553859 -1.88583114 -0.09453084]
 [-0.35915088 -0.79444967  0.23466354  2.50844874 -0.92454212]
 [ 1.41787157 -1.14367442 -0.66370009 -1.02207394  0.06134593]
 [-1.37274753  2.21762967 -1.04518771 -1.52565306 -0.03860794]
 [ 1.05347678 -0.15628405  0.74655211  0.33199514  0.42199143]]
