# Hello World

In [1]:
import numpy as np

In [2]:
matrix = np.array([[0., 1., 2.,], [1., 2., 3.,]])
matrix2 = np.array([[0., 1.,], [0., 1.,], [0., 1.,]])

In [3]:
print(matrix, matrix.ndim, matrix.shape)
print(matrix2, matrix2.ndim, matrix2.shape)

[[0. 1. 2.]
 [1. 2. 3.]] 2 (2, 3)
[[0. 1.]
 [0. 1.]
 [0. 1.]] 2 (3, 2)


In [4]:
print(np.concatenate([matrix[:, -1], matrix[0, :]], axis=0))
print(np.stack([matrix[0, :], np.concatenate([[0], matrix[:, -1]])], axis=0))

[2. 3. 0. 1. 2.]
[[0. 1. 2.]
 [0. 2. 3.]]


In [5]:
print(np.matmul(matrix, matrix2))
print(np.max(matrix, axis=0))
print(np.argmax(matrix, axis=0))
print(np.mean(matrix2, axis=-1))

[[0. 3.]
 [0. 6.]]
[1. 2. 3.]
[1 1 1]
[0.5 0.5 0.5]


In [6]:
print(np.reshape(matrix, [-1, 1]))
print(np.squeeze(np.reshape(matrix, [-1, 1])))
print(np.reshape(matrix2, [2, -1]))

[[0.]
 [1.]
 [2.]
 [1.]
 [2.]
 [3.]]
[0. 1. 2. 1. 2. 3.]
[[0. 1. 0.]
 [1. 0. 1.]]


In [7]:
print(np.zeros_like(matrix))
print(np.ones_like(matrix2.T))
print(np.random.randn(5, 5))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[ 1.00374212 -0.25762429 -0.19060134  0.35443104  0.84491693]
 [-0.69649935  1.16199803  0.76512409 -0.45696059  1.14969862]
 [ 1.22678783  0.21618514  0.34547734 -1.68846894 -1.71435571]
 [-1.12695567 -0.78586352 -1.3161807  -0.78344705 -0.06847782]
 [-2.30581115 -0.22400694  0.25622884 -0.80971456 -0.55559175]]
